# insurance.csv

- **Objective:** Convert categorical columns into numerical values using Label Encoding.

- **Steps:**
  1. Load and inspect the dataset.
  2. Explore the data.
  3. Identify the categorical columns.
  4. Encode the categorical columns using `LabelEncoder`.

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

### Load the Dataset

- Load the `insurance.csv` file using `pandas`.
- Display the first 5 rows to understand the structure of the dataset.

In [4]:
df = pd.read_csv('insurance.csv')
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

- استكشاف البيانات (`info` + `describe`)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [6]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### Identify Categorical Columns

- The categorical columns are: `sex`, `smoker`, and `region`.
- We can identify them automatically using `select_dtypes(include='object')`.

In [7]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
print("Categorical Columns :", categorical_cols)

Categorical Columns : ['sex', 'smoker', 'region']

### Convert Categorical Columns to Numerical Values

- Convert categorical columns into numerical values using `LabelEncoder`.
- Use `LabelEncoder` from the `sklearn` library.
- Apply the encoding to each column in `categorical_cols`.

In [9]:
le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

### Verify the Encoding

- Display `df.info()` to make sure that all columns have been converted to numeric data types.
- Display `df.head()` again to view the data after encoding.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   int64
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   int64
 5   region    1338 non-null   int64
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 73.3 KB

In [11]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

- Show THE DATA

In [12]:
styled_head = df.head(10).style.background_gradient(cmap='Blues')
styled_head

In [21]:
from IPython.display import HTML

def style_dataframe(df, title="DataFrame", subtitle=""):
    rows = ""
    for i, (_, row) in enumerate(df.iterrows(), start=1):
        cells = f'<td class="row-idx">{i}</td>'
        for col in df.columns:
            val = row[col]
            if col == 'smoker':
                badge_class = "badge-yes" if val == "yes" else "badge-no"
                cells += f'<td><span class="badge {badge_class}">{val}</span></td>'
            elif col == 'sex':
                cells += f'<td><span class="badge badge-sex">{val}</span></td>'
            elif col == 'region':
                cells += f'<td><span class="badge badge-reg">{val}</span></td>'
            elif col == 'charges':
                cells += f'<td class="num-hi">${val:,.0f}</td>'
            elif col in ['age', 'children']:
                cells += f'<td class="num">{val}</td>'
            elif col == 'bmi':
                cells += f'<td class="num">{val:.2f}</td>'
            else:
                cells += f'<td>{val}</td>'
        rows += f"<tr>{cells}</tr>"

    headers = '<th class="row-idx">#</th>' + "".join(f"<th>{col}</th>" for col in df.columns)

    html = f"""
    <style>
      .tbl-wrap {{
        font-family: 'Segoe UI', system-ui, sans-serif;
        padding: 24px;
        background: #0a0a0a;
        border-radius: 16px;
        border: 1px solid rgba(212, 175, 55, 0.25);
        max-width: 100%;
        overflow-x: auto;
      }}
      .tbl-title {{
        font-size: 18px;
        font-weight: 700;
        color: #d4af37;
        margin-bottom: 4px;
        letter-spacing: 0.3px;
      }}
      .tbl-sub {{
        font-size: 13px;
        color: #8a7a4a;
        margin-bottom: 16px;
      }}
      .styled-table {{
        width: 100%;
        border-collapse: separate;
        border-spacing: 0;
        font-size: 13px;
        border-radius: 12px;
        overflow: hidden;
        box-shadow: 0 0 40px rgba(212, 175, 55, 0.08);
        border: 1px solid rgba(212, 175, 55, 0.15);
      }}
      .styled-table thead tr {{
        background: linear-gradient(135deg, #d4af37 0%, #b8860b 50%, #d4af37 100%);
      }}
      .styled-table thead th {{
        padding: 14px 16px;
        text-align: left;
        color: #0a0a0a;
        font-weight: 700;
        font-size: 12px;
        text-transform: uppercase;
        letter-spacing: 0.8px;
      }}
      .styled-table tbody tr {{
        background: #111111;
        transition: all 0.2s ease;
      }}
      .styled-table tbody tr:nth-child(even) {{
        background: #161616;
      }}
      .styled-table tbody tr:hover {{
        background: #1f1a0e;
        box-shadow: inset 3px 0 0 #d4af37;
      }}
      .styled-table tbody td {{
        padding: 12px 16px;
        border-bottom: 1px solid rgba(212, 175, 55, 0.1);
        color: #e8e0c8;
      }}
      .row-idx {{
        color: #6b5d2f !important;
        font-weight: 600;
        text-align: center !important;
        width: 40px;
      }}
      .badge {{
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        display: inline-block;
        white-space: nowrap;
      }}
      .badge-yes {{
        background: rgba(212, 175, 55, 0.15);
        color: #ffd700;
        border: 1px solid #d4af37;
      }}
      .badge-no {{
        background: rgba(212, 175, 55, 0.05);
        color: #a0852c;
        border: 1px solid #5a4a1a;
      }}
      .badge-reg {{
        background: transparent;
        color: #d4af37;
        border: 1px solid rgba(212, 175, 55, 0.5);
      }}
      .badge-sex {{
        background: rgba(212, 175, 55, 0.08);
        color: #e6c25a;
        border: 1px solid rgba(212, 175, 55, 0.35);
      }}
      .num {{
        font-family: 'Consolas', monospace;
        color: #a89f8a;
        font-weight: 500;
      }}
      .num-hi {{
        font-family: 'Consolas', monospace;
        color: #ffd700;
        font-weight: 700;
        font-size: 13px;
      }}
      .tbl-footer {{
        font-size: 12px;
        color: #6b5d2f;
        margin-top: 12px;
        text-align: right;
      }}
    </style>
    <div class="tbl-wrap">
      <div class="tbl-title">{title}</div>
      <div class="tbl-sub">{subtitle}</div>
      <table class="styled-table">
        <thead><tr>{headers}</tr></thead>
        <tbody>{rows}</tbody>
      </table>
      <div class="tbl-footer">Showing {len(df)} rows &times; {len(df.columns)} columns</div>
    </div>
    """
    return HTML(html)


# استخدامه
style_dataframe(
    df.head(10),
    title="insurance.csv — first 10 rows",
    subtitle="Raw data before preprocessing"
)

In [13]:

mapping_data = {
    'Column': ['sex', 'sex', 'smoker', 'smoker', 'region', 'region', 'region', 'region'],
    'Original Value': ['male', 'female', 'yes', 'no', 'southeast', 'southwest', 'northeast', 'northwest'],
    'Encoded Value': [1, 0, 1, 0, 0, 1, 2, 3]
}

mapping_df = pd.DataFrame(mapping_data)

mapping_df.style.set_properties(**{'text-align': 'center'})